### ISSUE TITLE
Version of JDK

### ISSUE THREAD

**Issue by david-pfx** [DaveVoorhis/Spoing#1]
The top level readme needs to make it clear exactly which version(s) of the JDK this works with. There is a mention buried in a lower readme, and a link to something that appears to be the OpenJDK, but no installer. 

I know very little about this, but I've always used the Oracle Java SE downloads before, and that comes with an installer. Guidance is required.

**Comment by DaveVoorhis** [comment]
Good point. I'll add some relevant docs to the top-level README.

**Comment by david-pfx** [comment]
So what should I do now? I have an installation of JDK 8. Should I uninstall it? Will that break my other code?

 

As it stands both are now installed, but your scripts default to choosing the wrong one via the PATH. Do I need to modify the PATH or the script or both?

 

I’m sure people using Java all the time are familiar with these problems (they echo difficulties I’ve had in Python 2.7 vs 3.x), but for an occasional user they’re challenging.

 

Regards

David M Bennett FACS

  _____  

Andl - A New Database Language - andl.org

**Comment by DaveVoorhis** [comment]
Yes, this is all in a day's work for folks who regularly develop for Java.

Fortunately, the fix is easy. Download a JDK 13, unzip it to the _Deploy/demo directory of this project, and edit the script(s) you want to run so that they reference the Java executable in the JDK.

E.g., If you're on Windows change launchWinDesktop.cmd or launchWinWeb.cmd to replace 'java' with 'jdk-13\bin\java'.

**Comment by david-pfx** [comment]
Hi Dave

 

Not directly related, but I did all that and it broke the KNIME DSK. Eventually I found out KNIME is stuck on Java 8. I got that working by uninstalling Java 13 and installing https://adoptopenjdk.net/. How do I get both of them to play nicely?

 

Regards

David M Bennett FACS

  _____  

Puzzlang – Pattern language and Unity player for abstract single-player games and puzzles  -- http://www.polyomino.com <http://www.polyomino.com/>

**Comment by DaveVoorhis** [comment]
I presume the installation of Java 13 set the JAVA_HOME environment variable to point to Java 13?

If so, you can install Java 13 from http://openjdk.java.net, and install it per my note above from 08Nov2019. It won't require any environment variables set.

Unless... KNIME is searching for a Java installation. If so, there should be a way to point it at the desired JRE.

**Comment by david-pfx** [comment]
Hi Davie

 

Sorry, I don’t k now. I’ve installed (at various times) at least 5 different Javas. I see environment variables come and go, and registry keys, and odd config files and links placed here and there, with little consistency. I just don’t know what the main conventions are I should be tracking, but Oracle in particular is very confusing.

 

So I cleaned out everything I could find and installed AdoptOpenJDK 8 as directed. This turned up in Program Files (64 bit) and on my (system, not user) PATH, and nowhere else. I have no JAVA_HOME, and I have a CLASSPATH=“.”. 

 

KNIME Analytics Platform is just a cut-down Eclipse, but there is no sign of any specific JRE configuration (no Run config). Maybe Java is bundled in?

 

KNIME SDK is full blown Eclipse. The option to switch Java is available, and I assume this is what broke when it picked the wrong Java. It has now found OpenJDK on the PATH and it works. I assume KNIME searched the PATH (which is very reasonable, IMO).

 

So I guess I’ll install the latest OpenJDK and watch carefully to see if anything breaks. And steer clear of Oracle.

 

Regards

David M Bennett FACS

  _____  

Puzzlang – Pattern language and Unity player for abstract single-player games and puzzles  -- http://www.polyomino.com <http://www.polyomino.com/>
